<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AptitudeQuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('aptitude_questions')->insert([
            // 生活面
            [
                'category' => 1,
                'question' => '生活リズムを整えたい',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 100,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 1,
                'question' => 'コミュニケーションを向上させたい',
                'sort' => 10,
                'score_apple' => 50,
                'score_mint' => 100,
                'score_maple' => 50,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 1,
                'question' => '社会に出るために学びたい',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 100,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            // 社会面
            [
                'category' => 2,
                'question' => 'PCを基礎から学びたい',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 100,
                'score_maple' => 50,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 2,
                'question' => 'Microsoft Officeをできるようになりたい',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 50,
                'score_maple' => 50,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 2,
                'question' => '働くための体力や集中力を身につけたい',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 100,
                'score_maple' => 50,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 2,
                'question' => 'ビジネスマナーや敬語がわからない',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 50,
                'score_maple' => 0,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 2,
                'question' => '体を動かすことがしたい',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 50,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 2,
                'question' => '客や人とかかわることがしたい',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 50,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 2,
                'question' => 'お金をもらいながら働く準備がしたい',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 0,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            // 就職面
            [
                'category' => 3,
                'question' => '仕事のイメージができない',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 50,
                'score_maple' => 50,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => 'どんな仕事があるのか/自分にできる仕事があるのかわからない',
                'sort' => 10,
                'score_apple' => 50,
                'score_mint' => 100,
                'score_maple' => 0,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => '一人での就職活動が難しい',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 50,
                'score_maple' => 0,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => 'PCを使ったモノづくりがしたい',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 0,
                'score_maple' => 0,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => 'IT業界に興味がある',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 0,
                'score_maple' => 0,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => '大阪の緑の多いところへ行きたい',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 0,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => '2年以内での就職は難しそう',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 100,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => '農業に興味がある',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 0,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => '軽作業に興味がある',
                'sort' => 10,
                'score_apple' => 0,
                'score_mint' => 50,
                'score_maple' => 100,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
            [
                'category' => 3,
                'question' => '大阪市内が良い',
                'sort' => 10,
                'score_apple' => 100,
                'score_mint' => 100,
                'score_maple' => 0,
                'create_user_id' => 1,
                'update_user_id' => 1,
                'updated_at' => '2021-04-01 12:34:56',
                'created_at' => '2021-04-01 12:34:56',
            ],
        ]);
    }
}
